server:
  port: 8080

logging:
  level:
    root: info
  file:
    name: server.log
  logback:
    rollingpolicy:
      max-file-size: 1MB
      file-name-pattern: server.%d.%i.log

management:
  endpoints:
    enabled-by-default: true
    jmx:
      exposure:
        include: "*"
    web:
      exposure:
        include: "*"
        exclude: env
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ssm_demo?serverTimezone=UTC
    username: root
    password: 123456
  redis:
    host: localhost
    port: 6379
  mail:
    host: smtp.qq.com
    username: 1126422830@qq.com
    password: sqhfuaygumzvihga

#    druid:
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      url: jdbc:mysql://localhost:3306/ssm_demo?serverTimezone=UTC
#      username: root
#      password: 123456


mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#      table-prefix:

demo-server:
  ipAddress: 192.168.0.1
  port: 8086
  timeout: -1
  serverTimeout: 50
  dataSize: 1024

demo-data-source:
  driverClassName: com.mysql.jdbc.Driver456

test:
  prop: testValueOrigin

test-case:
  book:
    name: 书名-${random.value}
    author: 作者-${random.value}

rocketmq:
  namesrvAddr: localhost:9876

elasticsearch:
  host: 127.0.0.1
  port: 9200

utils:
  ip:
    cycle: 3
    cycle-reset: false
    mode: "detail"